permalink: /:year/:month/:day/:title.html
paginate: 10
# markdown: rdiscount
markdown: kramdown

# Author info
author: 
  name: Ting Lu
  email: vincentluting@hotmail.com
  link: https://www.linkedin.com/in/ting-lu-vincent/ 
  github: 

# Web info
title: Ting's Dream weaver
description: Ting's Dream weaver
url: https://tingsdreamweaver.github.io/
rss_url: 

# avatar & Favicon
gavatar: /public/upload/gavatar/gavatar.jpg
favicon: /public/upload/gavatar/favicon.ico

# google analytics settings
google_analytics_tracking_id: G-ZBBYH3JDCD
ga:
  id: G-ZBBYH3JDCD
  url: 

# disqus settings
disqus:
  shortname: tingdreamweaver

# gitment
gitment:
  id: ddbaadab5f5d810805c3
  secret: 13b91b306680f11a55713382529b83259ef56546

# 主题设置，自动激活某个标签
# active: Computer Science

# 首页除了最新文章外显示分类
cates: 
  - Learning

# 中文本地化
locals:
  tags: Tags
  about: About
  newest: Latest posts
plugins:
- jekyll-paginate